# fly.toml app configuration file generated for remix-blog-danding on 2024-07-16T16:37:10+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remix-blog-danding'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  SESSION_SECRET = "of_course_i_still_love_you"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
